version: '3.8'
services:
  fitbit2discord:
    image: iamtakagi/fitbit2discord:latest
    environment:
      SSL_PASSPHRASE: xxx
      HOST: 0.0.0.0
      PORT: 3000
      # 下記 5行 入力必須
      NAME: takagi 
      BASE_URL: https://localhost:3000
      FITBIT_REDIRECT_URL: https://localhost:3000/callback
      FITBIT_CLIENT_ID: xxx
      FITBIT_CLIENT_SECRET: xxx
      # カンマで区切ると複数追加可
      DISCORD_WEBOOK_URLS: https://discord.com/api/webhooks/xxx/xxx
      # 通知間隔 (秒数)
      NOTIFY_DELAY_SECONDS: 300
    ports:
      - 3000:3000
    volumes:
      - ./certs:/app/dist/certs
      - ./data:/app/dist/data
    restart: unless-stopped